spring:
  application:
    name: spring-security-jwt

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
#      username: abcd
#      password: "abcd1234"

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    data: classpath:data.sql
    initialization-mode: always

    server:
      port=9091:
jwt :
  secret: dfqwi256df75as@dfkhqfefhskjbj&37xc!@#dfkfslsdd57813sa
  refresh: dfqwi256df75as@dfkhqfefhskjbj&37xc!@#dfkfslsdd57813sa












